### ISSUE TITLE
Что делать выдаёт ошибку Traceback (most recent call last):
  File "/data/data/com.termux/files/home/TERORDNN-main/main.py", line 30, in <module>
    get_mail(database_file, search_value)
  File "/data/data/com.termux/files/home/TERORDNN-main/mail.py", line 18, in get_mail
    with open(database_file, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Terordnn.csv'

### ISSUE THREAD

**Issue by lololo000git** [afkenka/TERORDNN#1]

**Comment by Fly76jv** [comment]
желательно забыть про эту утилиту потому что тот кто ее создавал не запихнул в реп ее базу данных

**Comment by ghost** [comment]
поддерживаю.
